title: Kavicsblog
# baseurl: /kavicsblog

theme: jekyll-theme-tactile

permalink: /:title/


plugins:
- jekyll-paginate
- jekyll-archives

paginate: 20

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - kavicsblog.xcodeproj

