title: Kavicsblog
# baseurl: /kavicsblog

theme: jekyll-theme-tactile

permalink: /:title/

plugins:
- jekyll-paginate

paginate: 20

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
