title: Kavicsblog
baseurl: /kavicsblog

permalink: /:title/

plugins: [jekyll-paginate]
paginate: 20
#paginate_path: "/kavicsblog/page:num/"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

theme: jekyll-theme-tactile
