name: Kavicsblog
baseurl: /kavicsblog

#permalink: /kavicsblog/:title/

plugins: [jekyll-paginate]
paginate: 20
#paginate_path: "/kavicsblog/page:num/"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

#theme: jekyll-theme-console
#style: light
header_pages:
  - about.md

footer: '-- @% --'
